{{- if .Values.letsEncrypt.cloudflare.enabled }}
# ==============================================================================
# ExternalSecret for Cloudflare API Token
# ==============================================================================
# Extracts Cloudflare credentials from consolidated OCI Vault secret: cloudflare
# Vault secret contains: CLOUDFLARE_API_TOKEN, CLOUDFLARE_EMAIL, CLOUDFLARE_ZONE_ID
# Token requires Zone:DNS:Edit permissions for the domain
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-token: {{`"{{ .CLOUDFLARE_API_TOKEN }}"`}}
  dataFrom:
    - extract:
        # Consolidated vault secret: cloudflare
        key: {{ .Values.letsEncrypt.cloudflare.secretKey | default "cloudflare" }}
{{- end }}
