{{- if and .Values.certManager.enabled .Values.letsEncrypt.enabled }}
# ==============================================================================
# Let's Encrypt ClusterIssuer with Cloudflare DNS01 Solver
# ==============================================================================
# This ClusterIssuer uses ACME protocol with DNS01 challenge via Cloudflare
# DNS01 is required for wildcard certificates and when HTTP01 is not possible
#
# Prerequisites:
#   - cert-manager installed in cluster
#   - Cloudflare API token with Zone:DNS:Edit permissions
#   - cloudflare-api-token secret in cert-manager namespace
# ==============================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name | default "letsencrypt-prod" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  acme:
    # Let's Encrypt ACME server
    server: {{ .Values.letsEncrypt.server | default "https://acme-v02.api.letsencrypt.org/directory" }}
    # Email for certificate expiry notifications
    email: {{ .Values.letsEncrypt.email | required "letsEncrypt.email is required" }}
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    {{- if .Values.letsEncrypt.cloudflare.enabled }}
    # DNS01 solver using Cloudflare
    - dns01:
        cloudflare:
          # Cloudflare API token (not legacy API key)
          # Token needs Zone:DNS:Edit permissions for the domain
          apiTokenSecretRef:
            name: {{ .Values.letsEncrypt.cloudflare.apiTokenSecretRef.name | default "cloudflare-api-token" }}
            key: {{ .Values.letsEncrypt.cloudflare.apiTokenSecretRef.key | default "api-token" }}
      {{- if .Values.letsEncrypt.cloudflare.selector }}
      selector:
        {{- toYaml .Values.letsEncrypt.cloudflare.selector | nindent 8 }}
      {{- end }}
    {{- else }}
    # HTTP01 solver (default fallback)
    - http01:
        ingress:
          class: {{ .Values.ingress.className | default "nginx" }}
    {{- end }}
{{- end }}
---
{{- if and .Values.certManager.enabled .Values.letsEncrypt.enabled }}
# ==============================================================================
# Let's Encrypt Staging ClusterIssuer (for testing)
# ==============================================================================
# Use this issuer for testing to avoid Let's Encrypt rate limits
# Certificates will show as untrusted but validate the flow works
# ==============================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  acme:
    # Let's Encrypt staging server (higher rate limits, untrusted certs)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsEncrypt.email | required "letsEncrypt.email is required" }}
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    {{- if .Values.letsEncrypt.cloudflare.enabled }}
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ .Values.letsEncrypt.cloudflare.apiTokenSecretRef.name | default "cloudflare-api-token" }}
            key: {{ .Values.letsEncrypt.cloudflare.apiTokenSecretRef.key | default "api-token" }}
    {{- else }}
    - http01:
        ingress:
          class: {{ .Values.ingress.className | default "nginx" }}
    {{- end }}
{{- end }}
