{{- if .Values.externalSecretsOperator.monitoring.enabled }}
---
# ==============================================================================
# ServiceMonitor for External Secrets Operator
# ==============================================================================
# This ServiceMonitor enables Prometheus to scrape metrics from the External
# Secrets Operator, which provides critical metrics about secret sync status:
#
# Key metrics exposed:
# - externalsecret_status_condition: Ready status of ExternalSecret resources
# - external_secrets_sync_calls_total: Total sync attempts (success/error)
# - external_secrets_sync_calls_error: Failed sync attempts
# - externalsecret_sync_calls_duration: Sync operation duration
#
# These metrics are essential for dashboards and alerts to detect issues with
# secret synchronization from external secret stores (AWS Secrets Manager, etc.)
# ==============================================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets-operator
  namespace: {{ .Values.externalSecretsOperator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy AFTER kube-prometheus-stack (wave -2) installs CRDs
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # Don't fail if CRD missing during dry-run
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: controller
    release: prometheus  # Must match Prometheus serviceMonitorSelector
    {{- with .Values.externalSecretsOperator.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: external-secrets
  namespaceSelector:
    matchNames:
      - {{ .Values.externalSecretsOperator.namespace }}
  endpoints:
  - port: metrics
    interval: {{ .Values.externalSecretsOperator.monitoring.interval | default "30s" }}
    scrapeTimeout: {{ .Values.externalSecretsOperator.monitoring.scrapeTimeout | default "10s" }}
    path: /metrics
    scheme: http
    {{- with .Values.externalSecretsOperator.monitoring.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
