{{- if .Values.externalSecretsOperator.monitoring.enabled }}
---
# ==============================================================================
# Service for External Secrets Operator Metrics
# ==============================================================================
# The ESO pods expose metrics on port 8080 but no Service exists for them.
# This Service enables Prometheus to scrape ESO metrics via the ServiceMonitor.
#
# Metrics endpoint: http://external-secrets-metrics:8080/metrics
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: external-secrets-metrics
  namespace: {{ .Values.externalSecretsOperator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy with normal wave (CRDs not required for Service)
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: controller
    {{- with .Values.externalSecretsOperator.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
{{- end }}
