{{- if .Values.kubePrometheusStack.enabled }}
{{- if .Values.kubePrometheusStack.grafana.enabled }}
# ==============================================================================
# Grafana OAuth Secret Template
# ==============================================================================
# This creates an ExternalSecret to fetch the Grafana OAuth client secret
# from AWS Secrets Manager for Keycloak SSO integration
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: {{ .Values.kubePrometheusStack.namespace | default "monitoring" }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Environment variable format for Grafana
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ `{{ .clientSecret }}` }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: staging/keycloak/clients
        property: grafana-secret
{{- end }}
{{- end }}
