{{- if .Values.kubePrometheusStack.enabled }}
{{- if .Values.kubePrometheusStack.grafana.enabled }}
# ==============================================================================
# Grafana OAuth Secret Template
# ==============================================================================
# Extracts Grafana OAuth credentials from consolidated OCI Vault secrets
# - Admin password from: monitoring (GRAFANA_ADMIN_PASSWORD)
# - OAuth secret from: monitoring (GRAFANA_OIDC_SECRET)
# ==============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: {{ .Values.kubePrometheusStack.namespace | default "monitoring" }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name | default "oci-vault" }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "ClusterSecretStore" }}
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Environment variable format for Grafana
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{`"{{ .GRAFANA_OIDC_SECRET }}"`}}
        GF_SECURITY_ADMIN_PASSWORD: {{`"{{ .GRAFANA_ADMIN_PASSWORD }}"`}}
  dataFrom:
    - extract:
        # Consolidated vault secret: monitoring
        key: {{ .Values.externalSecrets.appSecretKey | default "monitoring" }}
{{- end }}
{{- end }}
