---
# ==============================================================================
# ClusterSecretStore for AWS Secrets Manager (Production)
# ==============================================================================
# Production configuration with:
#   - IRSA authentication (IAM Roles for Service Accounts)
#   - Region: ap-south-1 (update as needed)
#
# Prerequisites:
#   - EKS cluster with IRSA configured
#   - IAM role with SecretsManager read permissions
#   - External Secrets Operator installed
# ==============================================================================

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before ExternalSecrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
