# ==============================================================================
# ArgoCD Application - Flask Backend (Production)
# ==============================================================================
# Production EKS configuration:
#   - 3 replicas (HA)
#   - AWS Secrets Manager integration
#   - Production resources
#
# Sync Wave: 0
# ==============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/akthm/demo-k8s-gitops
    targetRevision: main
    path: helm-charts/flask-app
    helm:
      valueFiles:
        - values.yaml
        - values.prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  
  ignoreDifferences:
    # Ignore ExternalSecret status changes
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
    # Ignore Secret data changes (managed by ExternalSecrets Operator)
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
