# ==============================================================================
# ArgoCD Application - Platform App (Production - AWS EKS)
# ==============================================================================
# Unified umbrella chart deploying:
#   - Flask Backend (BFF mode) - 3+ replicas
#   - Nginx Frontend (React SPA) - 3+ replicas
#   - OAuth2-Proxy (Keycloak OIDC) - 3+ replicas
#   - Redis (HA with Sentinel)
#
# Production Configuration:
#   - AWS Secrets Manager for secrets
#   - External RDS or ElastiCache
#   - Let's Encrypt TLS (production issuer)
#   - HPA enabled for all components
#   - Strict security policies
#
# Sync Wave: 2 (after Keycloak and External Secrets)
# ==============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-app
    app.kubernetes.io/part-of: platform
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-prod-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: platform-prod-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: platform-prod-alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/akthm/demo-k8s-gitops
    targetRevision: main
    path: helm-charts/platform-app
    helm:
      valueFiles:
        - values.yaml
        - values.prod.yaml
      releaseName: platform

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /status
    - group: policy
      kind: PodDisruptionBudget
      jsonPointers:
        - /status
