apiVersion: v2
name: platform-app
description: |
  Unified Platform Application umbrella chart.
  Combines Flask backend, Nginx frontend, and oauth2-proxy BFF authentication
  with Redis session storage for Keycloak SSO integration.

type: application
version: 0.1.0
appVersion: "1.0.0"

# Keywords for discoverability
keywords:
  - flask
  - nginx
  - react
  - oauth2-proxy
  - keycloak
  - bff
  - sso

maintainers:
  - name: Platform Team
    email: platform@example.com

# Subchart dependencies
dependencies:
  # Flask backend API
  - name: flask-app
    version: ">=0.1.0"
    repository: "file://../flask-app"
    alias: backend
    condition: backend.enabled

  # Nginx frontend SPA
  - name: nginx-front
    version: ">=0.1.0"
    repository: "file://../nginx-front"
    alias: frontend
    condition: frontend.enabled

  # Redis for oauth2-proxy session storage
  - name: redis
    version: "20.6.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis
    condition: global.bff.redis.enabled
