---
# ==============================================================================
# cert-manager - Certificate Management (OCI Production)
# ==============================================================================
# Installs cert-manager with CRDs (ClusterIssuer, Certificate, etc.)
# Must run at sync wave -2 so CRDs exist before platform-ingress (wave 0)
# creates the letsencrypt-prod ClusterIssuer.
#
# Sync wave order:
#   -3: reflector
#   -2: cert-manager  <-- HERE (CRDs installed, controller running)
#    0: platform-ingress (ClusterIssuer created - CRDs now present)
# ==============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.4
    helm:
      values: |
        # Install cert-manager CRDs as part of this Helm release
        installCRDs: true
        # Resource tuning for OCI instances
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        webhook:
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
        cainjector:
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Required for large CRD annotations
      - PrunePropagationPolicy=foreground
