apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-incident-triage.fullname" . }}
  labels:
    {{- include "ai-incident-triage.labels" . | nindent 4 }}
data:
{{- with .Values.config }}
{{ toYaml . | indent 2 }}
{{- end }}
