{{- if and .Values.externalSecrets.enabled .Values.gitops.argo.preSyncSecretCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "flask-app.fullname" . }}-check-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "{{ .Values.gitops.argo.preSyncSecretCheck.syncWave }}"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: check
          image: bitnami/kubectl:1.30
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              ns="{{ .Release.Namespace }}"
              timeout="{{ .Values.gitops.argo.preSyncSecretCheck.timeoutSeconds }}"
              echo "PreSync: waiting up to ${timeout}s for required Secrets in namespace=${ns}"

              required="flask-app-db flask-app-db-credentials flask-app-secret flask-app-admin-credentials {{ .Values.jwt.existingSecret }}"

              end=$(( $(date +%s) + timeout ))
              for s in $required; do
                echo "Checking Secret: $s"
                while true; do
                  if kubectl -n "$ns" get secret "$s" >/dev/null 2>&1; then
                    echo "OK: $s exists"
                    break
                  fi
                  now=$(date +%s)
                  if [ "$now" -ge "$end" ]; then
                    echo "ERROR: Secret $s not found within ${timeout}s. External Secrets is likely failing."
                    exit 1
                  fi
                  sleep 2
                done
              done

              echo "All required Secrets exist."
{{- end }}
