{{- if .Values.externalSecrets.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flask-app.fullname" . }}-check-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flask-app.fullname" . }}-check-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
subjects:
  - kind: ServiceAccount
    name: {{ include "flask-app.fullname" . }}-check-secrets
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flask-app.fullname" . }}-check-secrets
{{- end }}
