{{- if .Values.externalSecrets.enabled }}
# ==============================================================================
# ExternalSecret for Database Encryption Keys
# ==============================================================================
# Extracts versioned encryption keys from OCI Vault secret: flask-app
# Vault secret contains: DATABASE_ENCRYPTION_KEY_V1, DATABASE_ENCRYPTION_KEY_V2, ...
#                        CURRENT_KEY_VERSION, ROTATION_DATE, MIGRATION_STATUS
#
# This secret enables:
#   - Multi-version key support (v1, v2, v3, etc.)
#   - Zero-downtime rotation (old keys remain available for decryption)
#   - Rotation detection via CURRENT_KEY_VERSION changes
#   - Monitoring via ROTATION_DATE and MIGRATION_STATUS
#
# Keys are mounted as individual files in /run/secrets/db_encryption_keys/:
#   - v1.key, v2.key, v3.key (versioned key files)
#   - current.version (contains active version identifier)
#   - rotation_date (timestamp of last rotation)
#   - migration_status (pending/in-progress/completed)
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: {{ .Values.secretNames.encryptionKeys | default "flask-app-encryption-keys" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: encryption
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create before database credentials
    helm.sh/resource-policy: keep       # Preserve during uninstall
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  {{- with .Values.externalSecrets.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries | default 5 }}
    retryInterval: {{ .retryInterval | default "10s" }}
    {{- if .retryIntervalMax }}
    retryIntervalMax: {{ .retryIntervalMax }}
    {{- end }}
  {{- end }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretNames.encryptionKeys | default "flask-app-encryption-keys" }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          {{- include "flask-app.labels" . | nindent 10 }}
          app.kubernetes.io/component: encryption
          encryption.mokhaback.dev/rotation-enabled: "true"
        annotations:
          encryption.mokhaback.dev/last-sync: {{`"{{ now | date \"2006-01-02T15:04:05Z07:00\" }}"`}}
          {{- if .Values.rotation.database.enabled }}
          encryption.mokhaback.dev/rotation-schedule: {{ .Values.rotation.database.schedule | quote }}
          encryption.mokhaback.dev/grace-period-days: {{ .Values.rotation.database.gracePeriodDays | quote }}
          {{- end }}
      data:
        # Versioned encryption keys (mounted as individual files)
        {{- if .Values.rotation.database.keyVersions }}
        {{- range .Values.rotation.database.keyVersions }}
        db_encryption_{{ . }}.key: {{`"{{ .DATABASE_ENCRYPTION_KEY_`}}{{ . | upper }}{{` }}"`}}
        {{- end }}
        {{- else }}
        # Default to v1 if keyVersions not specified
        db_encryption_v1.key: {{`"{{ .DATABASE_ENCRYPTION_KEY_V1 }}"`}}
        {{- end }}
        
        # Current version indicator (determines which key to use for encryption)
        db_encryption_current.version: {{`"{{ .CURRENT_KEY_VERSION | default \"v1\" }}"`}}
        
        # Rotation metadata for monitoring and detection
        {{- if .Values.rotation.database.enabled }}
        rotation_date: {{`"{{ .ROTATION_DATE | default \"\" }}"`}}
        migration_status: {{`"{{ .MIGRATION_STATUS | default \"none\" }}"`}}
        migrate_from_version: {{`"{{ .MIGRATE_FROM_VERSION | default \"\" }}"`}}
        grace_period_days: {{`"{{ .GRACE_PERIOD_DAYS | default \"`}}{{ .Values.rotation.database.gracePeriodDays }}{{`\" }}"`}}
        {{- end }}
  dataFrom:
    - extract:
        # Consolidated vault secret: flask-app
        key: {{ .Values.externalSecrets.appSecretKey | default "flask-app" }}
{{- end }}
