{{- if .Values.oidc.enabled }}
# ==============================================================================
# ExternalSecret for OIDC/Keycloak Credentials
# ==============================================================================
# Provides OAuth2/OIDC credentials for Flask backend authentication
# Required AWS Secrets Manager structure:
# {
#   "OIDC_CLIENT_ID": "flask-backend",
#   "OIDC_CLIENT_SECRET": "<keycloak-client-secret>"
# }
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "flask-app.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "flask-app.fullname" . }}-oidc
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.oidcKey }}
{{- end }}
