---
# ==============================================================================
# ExternalSecret for Flask Application Secrets
# ==============================================================================
# This resource fetches Flask application secrets (SECRET_KEY, API keys) from
# AWS Secrets Manager and creates a Kubernetes Secret in the backend namespace.
#
# AWS Secret: staging/backend/flask-app
# Target K8s Secret: flask-app-secrets
#
# Deployment: Add this file to your backend Helm chart at:
#   apps/staging/backend/templates/external-secret-flask.yaml
# ==============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-app-secret
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: flask-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: staging/backend/flask-app
