---
# ==============================================================================
# ExternalSecret for JWT Keys (RSA Key Pair)
# ==============================================================================
# This resource fetches JWT signing keys from AWS Secrets Manager and
# creates a Kubernetes Secret in the backend namespace.
#
# AWS Secret: staging/backend/jwt-keys
# Target K8s Secret: flask-app-jwt-keys
#
# The AWS secret should contain:
#   - JWT_PRIVATE_KEY: RSA private key (PEM format, 2048-bit or higher)
#   - JWT_PUBLIC_KEY: RSA public key (PEM format)
#
# To generate keys and store in AWS Secrets Manager:
#   1. Generate RSA key pair:
#      openssl genrsa -out private.pem 2048
#      openssl rsa -in private.pem -pubout -out public.pem
#
#   2. Create secret in AWS (replace newlines with \n):
#      aws secretsmanager create-secret \
#        --name staging/backend/jwt-keys \
#        --description "JWT RSA key pair for Flask backend" \
#        --secret-string "$(jq -n \
#          --arg private "$(cat private.pem)" \
#          --arg public "$(cat public.pem)" \
#          '{JWT_PRIVATE_KEY: $private, JWT_PUBLIC_KEY: $public}')" \
#        --region ap-south-1
#
#   3. Securely delete local key files:
#      shred -u private.pem public.pem
# ==============================================================================

{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "flask-app.fullname" . }}-jwt-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "flask-app.fullname" . }}-jwt-keys
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        JWT_PRIVATE_KEY: "{{ `{{ .JWT_PRIVATE_KEY }}` }}"
        JWT_PUBLIC_KEY: "{{ `{{ .JWT_PUBLIC_KEY }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.jwtKeysKey }}
{{- end }}
