{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretNames.databaseCredentials }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretNames.databaseCredentials }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        DATABASE_URL: "mysql+pymysql://{{`{{ .DB_USER }}`}}:{{`{{ .DB_PASSWORD }}`}}@{{`{{ .DB_HOST }}`}}:{{`{{ .DB_PORT }}`}}/{{`{{ .DB_NAME }}`}}"
        mysql-password: {{`"{{ .DB_PASSWORD }}"`}}
        mysql-root-password: {{`"{{ .DB_PASSWORD }}"`}}
        {{- range .Values.rotation.database.keyVersions }}
        db_encryption_{{ . }}.key: {{`"{{ .DATABASE_ENCRYPTION_KEY_`}}{{ . | upper }}{{` }}"`}}
        {{- end }}
        db_encryption_current.version: {{`"{{ .CURRENT_KEY_VERSION }}"`}}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.databaseKey }}
{{- end }}
