---
# ==============================================================================
# ExternalSecret for JWT Keys (RSA Key Pair)
# ==============================================================================
# Extracts JWT signing keys from consolidated OCI Vault secret: flask-app
# Vault secret contains: JWT_PRIVATE_KEY, JWT_PUBLIC_KEY
#
# To generate RSA keys and add to Terraform application_secrets:
#   1. Generate RSA key pair:
#      openssl genrsa -out private.pem 2048
#      openssl rsa -in private.pem -pubout -out public.pem
#
#   2. Update Terraform application_secrets.flask-app.data:
#      JWT_PRIVATE_KEY = file("private.pem")
#      JWT_PUBLIC_KEY  = file("public.pem")
#
#   3. Securely delete local key files:
#      shred -u private.pem public.pem
# ==============================================================================

{{- if .Values.externalSecrets.enabled and .Values.Config.AUTH_MODE == "local" }}
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: {{ include "flask-app.fullname" . }}-jwt-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  {{- with .Values.externalSecrets.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries | default 5 }}
    retryInterval: {{ .retryInterval | default "10s" }}
    {{- if .retryIntervalMax }}
    retryIntervalMax: {{ .retryIntervalMax }}
    {{- end }}
  {{- end }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "flask-app.fullname" . }}-jwt-keys
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        # JWT signing keys from consolidated flask-app secret
        JWT_PRIVATE_KEY: {{`"{{ .JWT_PRIVATE_KEY }}"`}}
        JWT_PUBLIC_KEY: {{`"{{ .JWT_PUBLIC_KEY }}"`}}
  dataFrom:
    - extract:
        # Consolidated vault secret: flask-app
        key: {{ .Values.externalSecrets.appSecretKey | default "flask-app" }}
{{- end }}
