{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretNames.adminCredentials }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  {{- with .Values.externalSecrets.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries | default 5 }}
    retryInterval: {{ .retryInterval | default "10s" }}
    {{- if .retryIntervalMax }}
    retryIntervalMax: {{ .retryIntervalMax }}
    {{- end }}
  {{- end }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretNames.adminCredentials }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.adminKey }}
{{- end }}
