---
# ==============================================================================
# ExternalSecret for Backend Database Credentials
# ==============================================================================
# This resource fetches database credentials from AWS Secrets Manager and
# creates a Kubernetes Secret in the backend namespace.
#
# AWS Secret: staging/backend/database
# Target K8s Secret: flask-app-db-credentials
#
# Deployment: Add this file to your backend Helm chart at:
#   apps/staging/backend/templates/external-secret-database.yaml
# ==============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-app-db-credentials
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: flask-app-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_USER: "{{ .DB_USER }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_HOST: "{{ .DB_HOST }}"
        DB_PORT: "{{ .DB_PORT }}"
        DB_NAME: "{{ .DB_NAME }}"
  dataFrom:
    - extract:
        key: staging/backend/database
