{{- if and .Values.externalSecrets.enabled (default true .Values.externalSecrets.initialAdminSecretEnabled) }}
# ==============================================================================
# ExternalSecret for Flask Admin Credentials
# ==============================================================================
# Note: For OCI staging, admin credentials are part of flask-app secret
# This template creates an empty secret as placeholder - configure initial
# admin via environment variables or application bootstrap
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: {{ .Values.secretNames.adminCredentials }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  {{- with .Values.externalSecrets.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries | default 5 }}
    retryInterval: {{ .retryInterval | default "10s" }}
    {{- if .retryIntervalMax }}
    retryIntervalMax: {{ .retryIntervalMax }}
    {{- end }}
  {{- end }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretNames.adminCredentials }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Initial admin user JSON for application bootstrap
        INITIAL_ADMIN_USER: '{"username":"admin","email":"admin@example.com"}'
  dataFrom:
    - extract:
        # Consolidated vault secret: flask-app
        key: {{ .Values.externalSecrets.appSecretKey | default "flask-app" }}
{{- end }}
