{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-db-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretNames.database }}
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        mysql-root-password: "{{`{{ .DB_PASSWORD }}`}}"
        mysql-password: "{{`{{ .DB_PASSWORD }}`}}"
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.databaseKey }}
        property: DB_PASSWORD
{{- end }}