---
# ==============================================================================
# ExternalSecret for Admin Credentials
# ==============================================================================
# This resource fetches initial admin user credentials from AWS Secrets Manager
# and creates a Kubernetes Secret in the backend namespace.
#
# AWS Secret: staging/backend/admin
# Target K8s Secret: flask-app-admin-credentials
#
# Deployment: Add this file to your backend Helm chart at:
#   apps/staging/backend/templates/external-secret-admin.yaml
# ==============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-app-admin-credentials
  namespace: backend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: flask-app-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INITIAL_ADMIN_USER: "{{ .INITIAL_ADMIN_USER }}"
  dataFrom:
    - extract:
        key: staging/backend/admin
