{{- if and .Values.externalSecrets.enabled .Values.db.enabled }}
# ==============================================================================
# ExternalSecret for MySQL Password (for MySQL subchart)
# ==============================================================================
# Uses consolidated OCI Vault secret (same as external-secret-database.yaml)
# Only created when the MySQL subchart is enabled (db.enabled: true)
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: mysql-db-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  {{- with .Values.externalSecrets.retrySettings }}
  retrySettings:
    maxRetries: {{ .maxRetries | default 5 }}
    retryInterval: {{ .retryInterval | default "10s" }}
    {{- if .retryIntervalMax }}
    retryIntervalMax: {{ .retryIntervalMax }}
    {{- end }}
  {{- end }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretNames.database }}
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        mysql-root-password: "{{`{{ .DB_PASSWORD }}`}}"
        mysql-password: "{{`{{ .DB_PASSWORD }}`}}"
  dataFrom:
    - extract:
        # Use consolidated vault secret (same key as external-secret-database.yaml)
        key: {{ .Values.externalSecrets.appSecretKey | default "flask-app" }}
{{- end }}