apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ if .Values.autoscaling.enabled }}1{{ else }}1{{ end }}
  selector:
    matchLabels:
      {{- include "flask-app.selectorLabels" . | nindent 6 }}
