# ==============================================================================
# ClusterSecretStore for LocalStack (Local Development)
# ==============================================================================
# Terragrunt provisions LocalStack with ESO integration.
# This store connects to LocalStack's Secrets Manager emulation.
#
# Prerequisites (provisioned by Terragrunt):
#   - LocalStack deployed in localstack namespace
#   - ESO credentials secret created
#   - Secrets populated in LocalStack
# ==============================================================================
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1  # LocalStack default region
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-credentials
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: localstack-credentials
            namespace: external-secrets
            key: secret-key
      # LocalStack endpoint - provisioned by Terragrunt
      additionalRoles: []
