{{- if .Values.externalSecrets.enabled }}
# ==============================================================================
# ExternalSecret for Keycloak Admin Credentials
# ==============================================================================
# Required AWS Secrets Manager structure:
# {
#   "admin-user": "admin",
#   "admin-password": "<secure-password>"
# }
# ==============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.adminCredentials.remoteRef }}
{{- end }}
