{{- if .Values.externalSecrets.enabled }}
# ==============================================================================
# ExternalSecret for Keycloak Admin Credentials
# ==============================================================================
# Extracts admin credentials from consolidated OCI Vault secret: keycloak
# Vault secret contains: admin_user, admin_password
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: {{`"{{ .admin_user }}"`}}
        admin-password: {{`"{{ .admin_password }}"`}}
  dataFrom:
    - extract:
        # Consolidated vault secret: keycloak
        key: {{ .Values.externalSecrets.appSecretKey | default "keycloak" }}
{{- end }}
