{{- if .Values.externalSecrets.enabled }}
# ==============================================================================
# ExternalSecret for Keycloak Database Credentials
# ==============================================================================
# Extracts DB credentials from consolidated OCI Vault secret: keycloak
# Vault secret contains: DB_USER, DB_PASSWORD, DB_URL (PostgreSQL JDBC URL)
# Works for both in-cluster PostgreSQL and external OCI ATP (via PG protocol)
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: keycloak-postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: keycloak-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # For Bitnami PostgreSQL subchart (if used)
        postgres-password: {{`"{{ .DB_PASSWORD }}"`}}
        password: {{`"{{ .DB_PASSWORD }}"`}}
        # For external database connection
        username: {{`"{{ .DB_USER }}"`}}
        {{- if .Values.database.wallet.enabled }}
        # Oracle JDBC URL using TNS alias with wallet location (wallet-based mTLS connection)
        jdbc-url: "jdbc:oracle:thin:@{{ .Values.database.wallet.tnsAlias }}?TNS_ADMIN=/opt/oracle/wallet"
        {{- else }}
        # PostgreSQL JDBC URL for Oracle ATP (using PostgreSQL protocol)
        jdbc-url: {{`"{{ .DB_URL }}"`}}
        {{- end }}
  dataFrom:
    - extract:
        # Consolidated vault secret: keycloak
        key: {{ .Values.externalSecrets.appSecretKey | default "keycloak" }}
{{- end }}
