{{- if .Values.externalSecrets.enabled }}
# ==============================================================================
# ExternalSecret for Keycloak Database Credentials
# ==============================================================================
# Extracts DB credentials from consolidated OCI Vault secret: keycloak
# Vault secret contains: DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME
# Works for both in-cluster PostgreSQL and external OCI ATP
# ==============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: keycloak-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # For Bitnami PostgreSQL subchart
        postgres-password: {{`"{{ .DB_PASSWORD }}"`}}
        password: {{`"{{ .DB_PASSWORD }}"`}}
        # For external database connection
        username: {{`"{{ .DB_USER }}"`}}
        DB_HOST: {{`"{{ .DB_HOST }}"`}}
        DB_PORT: {{`"{{ .DB_PORT }}"`}}
        DB_NAME: {{`"{{ .DB_NAME }}"`}}
  dataFrom:
    - extract:
        # Consolidated vault secret: keycloak
        key: {{ .Values.externalSecrets.appSecretKey | default "keycloak" }}
{{- end }}
