global:
  namespace: transit-demo

storage:
  mirror:
    enabled: true
    size: 50Gi
    storageClassName: oci-bv

# Use pushed images accessible from OKE nodes.
# Replace repositories/tags with your registry artifacts.
connect:
  image:
    repository: docker.io/akthm/etl-connect
    tag: "latest"

simulator:
  image:
    repository: docker.io/akthm/etl-simulator
    tag: "latest"

prefectRunner:
  image:
    repository: docker.io/akthm/etl-prefect-runner
    tag: "latest"

lakeConsumer:
  enabled: false
  image:
    repository: docker.io/akthm/etl-lake-consumer
    tag: "latest"

# Keep optional components off for free-tier profile.
minio:
  enabled: false

ingress:
  enabled: true
  className: nginx
  basicAuth:
    enabled: false
    secretName: transit-demo-basic-auth
  tls:
    enabled: true
    secretName: platform-oci-staging-tls
  portal:
    host: transit-demo.adaas-il.com
  prefect:
    host: prefect-transit.adaas-il.com
  pgwebSource:
    host: pgweb-source-transit.adaas-il.com
  pgwebMirror:
    host: pgweb-mirror-transit.adaas-il.com
  minio:
    enabled: false
