global:
  namespace: transit-demo

storage:
  mirror:
    enabled: true
    size: 50Gi
    storageClassName: oci-bv

# Use pushed images accessible from OKE nodes.
# Replace repositories/tags with your registry artifacts.
connect:
  image:
    repository: docker.io/akthm/etl-connect
    tag: "latest"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

simulator:
  image:
    repository: docker.io/akthm/etl-simulator
    tag: "latest"
  resources:
    requests:
      cpu: 20m
      memory: 96Mi
    limits:
      cpu: 120m
      memory: 192Mi

prefectRunner:
  image:
    repository: docker.io/akthm/etl-prefect-runner
    tag: "latest"
  resources:
    requests:
      cpu: 40m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 512Mi

postgres:
  source:
    resources:
      requests:
        cpu: 60m
        memory: 192Mi
      limits:
        cpu: 250m
        memory: 384Mi
  mirror:
    resources:
      requests:
        cpu: 80m
        memory: 320Mi
      limits:
        cpu: 400m
        memory: 768Mi

redpanda:
  resources:
    requests:
      cpu: 50m
      memory: 320Mi
    limits:
      cpu: 300m
      memory: 768Mi

prefect:
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi

lakeConsumer:
  enabled: false
  image:
    repository: docker.io/akthm/etl-lake-consumer
    tag: "latest"

# Keep optional components off for free-tier profile.
minio:
  enabled: false

ingress:
  enabled: true
  className: nginx
  basicAuth:
    enabled: false
    secretName: transit-demo-basic-auth
  tls:
    enabled: true
    secretName: platform-oci-staging-tls
  portal:
    host: transit-demo.adaas-il.com
  prefect:
    host: prefect-transit.adaas-il.com
  pgwebSource:
    host: pgweb-source-transit.adaas-il.com
  pgwebMirror:
    host: pgweb-mirror-transit.adaas-il.com
  minio:
    enabled: false
