---
# ==============================================================================
# ClusterSecretStore for OCI Vault (OCI Staging)
# ==============================================================================
# OCI Vault configuration with:
#   - Instance Principal authentication (for OKE workloads)
#   - Region: il-jerusalem-1 (Israel Jerusalem)
#   - Vault name pattern: ${cluster_name}-vault (e.g., oke-staging-vault)
#
# Terraform creates:
#   - Dynamic group for OKE nodes (create_dynamic_group = true)
#   - IAM policy for vault access (create_iam_policy = true)
#
# Vault Secrets Structure (application_secrets):
#   - flask-app: All Flask secrets (DB, JWT, OIDC, encryption keys)
#   - keycloak: Admin credentials, DB, client secrets
#   - cloudflare: API token for DNS01 challenge
#   - monitoring: Grafana admin and OIDC secrets
#
# Prerequisites:
#   - OKE cluster with Instance Principal enabled
#   - Terraform vault module applied
#   - External Secrets Operator v0.9.0+ installed
# ==============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before ExternalSecrets
spec:
  provider:
    oracle:
      # OCI Vault OCID - Terraform output: module.vault.vault_id
      # Vault name: oke-staging-vault
      vault: "ocid1.vault.oc1.il-jerusalem-1.REPLACE_WITH_VAULT_OCID"
      region: "il-jerusalem-1"
      # Instance Principal authentication (configured by Terraform)
      # Dynamic group: oke-staging-workload-identity
      # Policy grants: read secret-bundles, read vaults
      auth:
        secretRef:
          privatekey:
            name: ""
            key: ""
          fingerprint:
            name: ""
            key: ""
        # Instance Principal - leave secretRef empty
        # ESO auto-detects OKE instance metadata service
