---
# ==============================================================================
# Flask Backend Application - OCI Staging
# ==============================================================================
# Deploys Flask app with:
#   - External OCI Autonomous Database (PostgreSQL)
#   - OCI Vault for secrets management
#   - Wallet-based mTLS connection to ATP
# ==============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/akthm/demo-k8s-gitops
    targetRevision: HEAD
    path: helm-charts/flask-app
    helm:
      valueFiles:
        - values.yaml
        - values.oci-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
