apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-front.fullname" . }}
  labels:
    {{- include "nginx-front.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx-front.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from Ingress Controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    # Allow from anywhere on port 80/443 (if no ingress controller labels)
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow to backend API
    - to:
        - namespaceSelector:
            matchLabels:
              name: backend
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: flask-app
      ports:
        - protocol: TCP
          port: 5000
    # Allow external HTTPS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
