---
# ==============================================================================
# ClusterSecretStore for AWS Secrets Manager
# ==============================================================================
# This resource configures External Secrets Operator to use AWS Secrets Manager
# as the backend for secrets in the ap-south-1 region.
#
# Authentication: Uses IRSA (IAM Roles for Service Accounts) configured via
# Terraform in the eks_blueprints_addons module.
#
# Deployment: Add this file to your GitOps repo at:
#   apps/staging/cluster-secret-store.yaml
# ==============================================================================

apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before ExternalSecrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
