apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # DEPLOY FIRST
spec:
  project: default

  source:
    repoURL: https://github.com/akthm/demo-k8s-gitops
    targetRevision: main
    path: helm-charts/flask-app
    helm:
      valueFiles:
        - values.yaml
        - values.stage.yaml
      parameters:
        - name: image.tag
          value: "1.0.15"

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      # Optional:
      # - PruneLast=true
