# ==============================================================================
# ArgoCD Application - Keycloak Identity Provider
# ==============================================================================
# Deploys Keycloak as the central SSO provider for the platform
# Sync Wave: -3 (deploys before monitoring-stack at -2)
# ==============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/akthm/demo-k8s-gitops
    targetRevision: main
    path: helm-charts/keycloak
    helm:
      releaseName: keycloak
      valueFiles:
        - values.yaml
        - values.stage.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    # Ignore Secret data changes (managed by ExternalSecrets Operator)
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    # Ignore ExternalSecret status changes (refreshTime, conditions, etc.)
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
        - /data
