apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Deploy before flask-backend (wave 0)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/akthm/demo-k8s-gitops
    targetRevision: main
    path: helm-charts/monitoring-stack
    helm:
      releaseName: monitoring-stack
      valueFiles:
        - values.yaml
        - values.stage.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # Parent app in argocd namespace
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health check for child Application resources
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/source/targetRevision
