{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled .Values.ingress.basicAuth.htpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.basicAuth.secretName }}
  labels:
    {{- include "transit-demo.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.ingress.basicAuth.htpasswd | b64enc }}
{{- end }}
