{{- if .Values.global.bff.enabled }}
{{- if not .Values.global.externalSecrets.enabled }}
# 
# BFF Internal Secret
# ==============================================================================
# This shared secret validates that requests to the backend come from the
# nginx gateway, not from external sources bypassing authentication.
# ==============================================================================
# WARNING: This secret uses a placeholder============================================================================== value!
# In production, use ExternalSecrets or set values via --set flag:
#   helm install ... --set global.bff.internalSecret=$(openssl rand -base64 32)
# 
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-app.bff.internalSecretName" . }}
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff-auth
type: Opaque
stringData:
  # Shared secret between nginx and backend
  # Generate with: openssl rand -base64 32
  internal-secret: {{ .Values.global.bff.internalSecret | default "CHANGE-ME-internal-secret-32-bytes" | quote }}
{{- end }}
{{- end }}
