{{- if and .Values.global.bff.enabled .Values.global.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform-app.bff.internalSecretName" . }}
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff-auth
spec:
  refreshInterval: {{ .Values.global.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.global.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.global.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "platform-app.bff.internalSecretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    # BFF internal secret shared between nginx and backend
    - secretKey: internal-secret
      remoteRef:
        key: {{ .Values.global.externalSecrets.basePath }}/bff
        property: INTERNAL_SECRET
{{- end }}
