{{- if .Values.oauth2Proxy.enabled }}
{{- if not .Values.global.externalSecrets.enabled }}
# ==============================================================================
# OAuth2 Proxy Secrets
# ==============================================================================
# WARNING: This secret uses placeholder values!
# In production, use ExternalSecrets or set values via --set flag
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-app.oauth2proxy.secretName" . }}
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
type: Opaque
stringData:
  # Keycloak client secret for BFF proxy
  # Get this from Keycloak Admin Console -> Clients -> bff-proxy -> Credentials
  client-secret: "CHANGE-ME-keycloak-client-secret"
  
  # Cookie encryption secret (must be 16, 24, or 32 bytes for AES)
  # Generate with: openssl rand -base64 32 | head -c 32
  cookie-secret: "CHANGE-ME-cookie-secret-32-bytes"
{{- end }}
{{- end }}
