{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-app.oauth2proxy.name" . }}
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  type: {{ .Values.oauth2Proxy.service.type }}
  ports:
    - name: http
      port: {{ .Values.oauth2Proxy.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 44180
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "platform-app.oauth2proxy.selectorLabels" . | nindent 4 }}
{{- end }}
