{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "platform-app.fullname" . }}-nginx-gateway
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-gateway
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "platform-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx-gateway

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "platform-app.oauth2proxy.name" . }}
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "platform-app.oauth2proxy.selectorLabels" . | nindent 6 }}
{{- end }}
