{{- if .Values.externalSecrets.enabled }}
# ==============================================================================
# ExternalSecret for ArgoCD OIDC Client Secret
# ==============================================================================
# Extracts ArgoCD client secret from consolidated OCI Vault secret: keycloak
# Vault secret contains: argocd_secret
# ==============================================================================
apiVersion: 'external-secrets.io/{{ .Values.externalSecrets.apiVersion | default "v1beta1" }}'
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: argocd-oidc
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        client-secret: {{`"{{ .argocd_secret }}"`}}
  dataFrom:
    - extract:
        # Consolidated vault secret: keycloak (contains client secrets)
        key: {{ .Values.externalSecrets.appSecretKey | default "keycloak" }}
{{- end }}
